version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.18.0
    steps:
      - run: sudo apt-get install rsync
      - add_ssh_keys
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yar
      - run:
          name: build-project
          command: yarn generate
      - run:
         name: "SSH KEYSCAN get knownh hosts"
         command: ssh-keyscan -H ${SERVER_NAME} >> ~/.ssh/known_hosts
      - run:
         name: "Rsync, remove old generated files and place the new ones"
         command: rsync -avce ssh --delete ./dist/ ${USER_VPS}@${SERVER_NAME}:${CUSTOM_PATH}